version: 2
jobs:
  build:
    docker:
      - image: fedora:28
    steps:
      - checkout
      - run:
          name: Update
          command: dnf update -y
      - run:
          name: Install rpmfusion.org repository
          command: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - run:
          name: Install tools, Qt and ffmpeg
          command: dnf install -y which sudo make hostname openssh-clients rpm-build qt qt5-qtbase-devel qt5-qtsvg ffmpeg ffmpeg-devel
      - run:
          name: Build
          command: ./scripts/build.sh --clean && ./scripts/create_package.sh --rpm --distro=f$(rpm -E %fedora)
      - run:
          name: Upload
          command: scp -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
