version: 2
jobs:
  build-centos7:
    docker:
      - image: centos:centos7
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_centos.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=el$(rpm -E %centos)
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-fedora32:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_fedora.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=f$(rpm -E %fedora)
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-opensuseleap:
    docker:
      - image: opensuse/leap
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_opensuse.sh
      - run:
          name: Build
          command: if [ -e /etc/os-release ]; then . /etc/os-release; else . /usr/lib/os-release; fi && ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=suse$VERSION_ID
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-debian9:
    docker:
      - image: debian:9
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_debian.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=debian$(lsb_release -r -s)
      - run:
          name: Alien
          command: alien -k -d build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT *.deb $UPLOAD_USER@$UPLOAD_HOST:.
  build-ubuntu2004:
    docker:
      - image: ubuntu:focal
    steps:
      - checkout
      - run:
          name: Prerequisites
          command: ./scripts/prereqs_debian.sh
      - run:
          name: Build
          command: ./scripts/build.sh --clean --max-nc=2 && ./scripts/create_package.sh --rpm --distro=ubuntu$(lsb_release -r -s)
      - run:
          name: Alien
          command: alien -k -d build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT *.deb $UPLOAD_USER@$UPLOAD_HOST:.
workflows:
  version: 2
  build_all:
    jobs:
      - build-centos7
      - build-fedora32
      - build-opensuseleap
      - build-debian9
      - build-ubuntu2004
