version: 2
jobs:
  build-fedora28:
    docker:
      - image: fedora:28
    steps:
      - checkout
      - run:
          name: Update
          command: dnf update -y
      - run:
          name: Install rpmfusion.org repository
          command: dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      - run:
          name: Install tools, Qt and ffmpeg
          command: dnf install -y which sudo make hostname openssh-clients rpm-build qt qt5-qtbase-devel qt5-qtsvg ffmpeg ffmpeg-devel
      - run:
          name: Build
          command: ./scripts/build.sh --clean && ./scripts/create_package.sh --rpm --distro=f$(rpm -E %fedora)
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm $UPLOAD_USER@$UPLOAD_HOST:.
  build-ubuntu1804:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Update
          command: apt-get update -q
      - run:
          name: Install software-properties-common
          command: apt-get install -y software-properties-common
      - run:
          name: Install tools, Qt and ffmpeg
          command: apt-get install -y pkg-config build-essential alien openssh-client rpm qt5-default libavutil-dev libavformat-dev libswscale-dev libavdevice-dev ffmpeg
      - run:
          name: Build
          command: ./scripts/build.sh --clean && ./scripts/create_package.sh --rpm --distro=ubuntu$(lsb_release -r -s)
      - run:
          name: Alien
          command: alien -k -d build-Release/packages/rpmbuild/RPMS/$(uname -m)/*.rpm
      - run:
          name: Upload
          command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $UPLOAD_PORT *.deb $UPLOAD_USER@$UPLOAD_HOST:.
workflows:
  version: 2
  build_all:
    jobs:
      - build-fedora28
      - build-ubuntu1804
